export enum ModalActions {
    LOADING,
    CREATING_USER,
    CREATE,
    EDIT,
    EDIT_PASSWORD,
    DELETE,
    USER_CREATED,
    USER_REMOVED,
    EXIT,

    ERROR_SAVE,
    ERROR_DELETE,
    ERROR_USER_LOADING,
    ERROR_HABITS_LOADING,

    ERROR_HABIT_PROGRESS_SAVE,

    EXPIRED,
    ERROR_SESSION,
    ERROR_IMAGE,
    ERROR_CONNECTION,
    ERROR_SERVER,
    CUSTOM
}